@startuml classes_optimize
set namespaceSeparator none

package Optimize {
  class "MVOptimizer" as garpar.optimize.mean_variance.MVOptimizer {
    market_neutral: Bool
    method: String
    risk_free_rate: [Float]
    target_return: Float
    target_risk: Float
    weight_bounds: (Float, Float)
  }
  class "Markowitz" as garpar.optimize.mean_variance.Markowitz {
    market_neutral: Bool
    target_return: Float
    target_risk: Float
    weight_bounds: (Float, Float)
  }
  class "MeanVarianceFamilyMixin" as garpar.optimize.opt_base.MeanVarianceFamilyMixin {
    family : str
  }
  class "OptimizerABC" as garpar.optimize.opt_base.OptimizerABC {
    family : object
    get_optimizer_family()
    optimize(ss)
  }
}

garpar.optimize.mean_variance.MVOptimizer -u-> garpar.optimize.opt_base.MeanVarianceFamilyMixin
garpar.optimize.mean_variance.MVOptimizer -u-> garpar.optimize.opt_base.OptimizerABC
garpar.optimize.mean_variance.Markowitz -u-> garpar.optimize.opt_base.MeanVarianceFamilyMixin
garpar.optimize.mean_variance.Markowitz -u-> garpar.optimize.opt_base.OptimizerABC

@enduml
