@startuml classes_core
set namespaceSeparator none
package Core{

  class "StocksSet" as garpar.core.stocks_set.StocksSet {
    entropy
    stocks
    weights
    window_size
    as_prices()
    as_returns()
    copy()
    delisted_prune()
    from_dfkws(prices, weights, entropy, window_size, stocks)
    refresh_entropy()
    scale_weights()
    to_dataframe()
    to_hdf5(stream_or_buff)
    weights_prune(threshold)
  }
  class "StocksSetPlotterAccessor" as garpar.core.plot_acc.StocksSetPlotterAccessor {
    box(returns)
    heatmap(returns)
    hist(returns)
    kde(returns)
    line(returns)
    ogive(returns)
    wbox()
    wheatmap()
    whist()
    wkde()
  }
  class "PricesAccessor" as garpar.core.prices_acc.PricesAccessor {
    log()
    log10()
    log2()
    mad(skipna)
    mean_tendency_size()
  }
  class "RiskAccessor" as garpar.core.risk_acc.RiskAccessor {
    ss_beta
    ss_var
    var
    stocks_set_beta()
    stocks_set_variance(covariance, covariance_kw)
    sharpe_ratio()
    stock_beta(market_prices, log_returns)
    treynor_ratio()
    value_at_risk()
  }
  class "CorrelationAccessor" as garpar.core.covcorr_acc.CorrelationAccessor {
    exp_corr()
    ledoit_wolf_corr()
    oracle_approximating_corr()
    sample_corr()
    semi_corr()
  }
  class "CovarianceAccessor" as garpar.core.covcorr_acc.CovarianceAccessor {
    exp_cov()
    ledoit_wolf_cov(shrinkage_target)
    oracle_approximating_cov()
    sample_cov()
    semi_cov()
  }
  class "DiversificationMetricsAccessor" as garpar.core.div_acc.DiversificationMetricsAccessor {
    cross_entropy(benchmark_weights)
    ke_zang_entropy()
    mrc()
    pdi()
    ratio()
    zheng_entropy()
  }
  class "ExpectedReturnsAccessor" as garpar.core.ereturns_acc.ExpectedReturnsAccessor {
    capm()
    emah()
    mah()
  }
  class "UtilitiesAccessor" as garpar.core.utilities_acc.UtilitiesAccessor {
    ss_return
    qutility
    ex_ante_tracking_error()
    ex_post_tracking_error()
    stocks_set_return()
    quadratic_utility()
  }
}

garpar.core.stocks_set.StocksSet o-- garpar.core.div_acc.DiversificationMetricsAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.plot_acc.StocksSetPlotterAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.risk_acc.RiskAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.prices_acc.PricesAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.covcorr_acc.CovarianceAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.covcorr_acc.CorrelationAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.ereturns_acc.ExpectedReturnsAccessor
garpar.core.stocks_set.StocksSet o-- garpar.core.utilities_acc.UtilitiesAccessor

@enduml
