# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  workflow_dispatch:
    inputs:
        pypi_token:
          description: 'PyPI API Token'
          required: true
  # release:
  #   types: [created]

jobs:
  testing:
    uses: quatrope/garpar/.github/workflows/tests.yml@0264fbc76b79401c1d60bf9249eb2f9e45af4458

  pypi-publish:
    name: upload release to PyPI

    needs: testing

    runs-on: ubuntu-latest

    # environment:
    #   name: pypi
    #   url: https://pypi.org/p/garpar

    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build
          python -m build --sdist --wheel
          twine upload --username __token__ --password ${{ github.event.inputs.pypi_token }} dist/*

      # - name: Publish package distributions to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     repository-url: https://test.pypi.org/legacy/
